# Identificador único do projeto no SonarQube
sonar.projectKey=barbearia-backend

# Nome exibido na interface do SonarQube
sonar.projectName=GrupoB-barbearia-backend

# Endereço do servidor
sonar.host.url=https://110e-2804-1b2-aa40-c9e6-6d75-fc2c-93ca-8aaa.ngrok-free.app/

# Autenticação por token (Opção A)
sonar.token=sqa_68336917d7bbec897907bb8844fd2839cd3aba3c

# OU por usuário e senha (Opção B)
# sonar.login=seu_usuario
# sonar.password=sua_senha

# Pasta(s) com o código-fonte
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes