DROP TABLE IF EXISTS historico_atendimento;
DROP TABLE IF EXISTS agendamento;
DROP TABLE IF EXISTS servico;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS barbeiro;

-- Tabela Barbeiro (Herdando campos de EntidadeBase)
CREATE TABLE barbeiro (
                          barbeiro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR(255),
                          email VARCHAR(255),
                          telefone VARCHAR(255),
                          created_at TIMESTAMP,
                          created_by VARCHAR(255),
                          updated_at TIMESTAMP,
                          updated_by VARCHAR(255)
);

-- Tabela Cliente (Herdando campos de EntidadeBase)
CREATE TABLE cliente (
                         cliente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR(255),
                         email VARCHAR(255),
                         telefone VARCHAR(255),
                         created_at TIMESTAMP,
                         created_by VARCHAR(255),
                         updated_at TIMESTAMP,
                         updated_by VARCHAR(255)
);

-- Tabela Servico (Herdando campos de EntidadeBase)
CREATE TABLE servico (
                         servico_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR(255),
                         descricao VARCHAR(255),
                         preco DECIMAL(10, 2),
                         created_at TIMESTAMP,
                         created_by VARCHAR(255),
                         updated_at TIMESTAMP,
                         updated_by VARCHAR(255)
);

-- Tabela Agendamento (Herdando campos de EntidadeBase)
CREATE TABLE agendamento (
                             agendamento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             horario TIMESTAMP,
                             status VARCHAR(50),
                             cliente_id BIGINT,
                             servico_id BIGINT,
                             barbeiro_id BIGINT,
                             created_at TIMESTAMP,
                             created_by VARCHAR(255),
                             updated_at TIMESTAMP,
                             updated_by VARCHAR(255),
                             CONSTRAINT fk_agendamento_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id),
                             CONSTRAINT fk_agendamento_servico FOREIGN KEY (servico_id) REFERENCES servico(servico_id),
                             CONSTRAINT fk_agendamento_barbeiro FOREIGN KEY (barbeiro_id) REFERENCES barbeiro(barbeiro_id)
);

-- Tabela HistoricoAtendimento (Herdando campos de EntidadeBase)
CREATE TABLE historico_atendimento (
                                       historico_atendimento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       data TIMESTAMP,
                                       valor_pago DECIMAL(10, 2),
                                       cliente_id BIGINT NOT NULL,
                                       servico_id BIGINT NOT NULL,
                                       barbeiro_id BIGINT NOT NULL,
                                       created_at TIMESTAMP,
                                       created_by VARCHAR(255),
                                       updated_at TIMESTAMP,
                                       updated_by VARCHAR(255),
                                       CONSTRAINT fk_historico_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id),
                                       CONSTRAINT fk_historico_servico FOREIGN KEY (servico_id) REFERENCES servico(servico_id),
                                       CONSTRAINT fk_historico_barbeiro FOREIGN KEY (barbeiro_id) REFERENCES barbeiro(barbeiro_id)
);