CREATE TABLE IF NOT EXISTS `cliente` (
    cliente_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(20) UNIQUE,
    telefone VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS `servico` (
    servico_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    preco DOUBLE NOT NULL,
    descricao VARCHAR(255)
);